polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path, include
from . import views
# from .api import TodoList, TodoDetail

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('todo_list_partial', views.todo_list_partial, name='todo_list_partial'),
    path('todo_details_partial/<int:pk>',
         views.todo_details_partial, name='todo_details_partial'),
    path('create', views.create, name='create'),
    path('rerank', views.rerank, name='rerank'),
    # path('api/v1', TodoList.as_view()),
    # path('api/v1/<int:pk>', TodoDetail.as_view()),
    # path('api/v1/rest-auth', include('rest_framework.urls')),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self) -> str:
        return f'{self.question_text} - {self.pub_date}'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.question.question_text} - {self.choice_text} - {self.votes}'

todo/models.py
from django.db import models, transaction


class Todo(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    text = models.TextField()
    rank = models.IntegerField(db_index=True)

    class Meta:
        ordering = ['rank']

    def __str__(self):
        return f'({self.rank}) - {self.pk} - {self.title} - {self.text}'

    @classmethod
    def create(cls, title=title, text=text):
        cls.objects.create(
            title=title,
            text=text,
            rank=cls.highest_rank + 1)

    def delete(self, *args, **kwargs):
        self.rerank(type(self).highest_rank)
        super(type(self), self).delete(*args, **kwargs)

    @classmethod
    @property
    def highest_rank(cls):
        return int(cls.objects.all().aggregate(models.Max('rank'))['rank__max'] or 0)

    @classmethod
    def rerank_by_list(cls, reranked):
        todos = [todo.pk for todo in cls.objects.all()]
        for i, samples in enumerate(zip(todos, reranked)):
            if not samples[0] == samples[1]:
                new_i_index = reranked.index(todos[i])
                Todo.objects.get(pk=todos[i]).rerank(new_i_index+1)

    def rerank(self, new_rank):
        with transaction.atomic():
            if self.rank == new_rank:
                return
            elif new_rank < self.rank:
                delta = 1
                todos = type(self).objects.filter(
                    rank__gte=new_rank).filter(rank__lte=self.rank)
            else:
                delta = -1
                todos = type(self).objects.filter(
                    rank__gte=self.rank).filter(rank__lte=new_rank)

            for todo in todos:
                if todo.rank == self.rank:
                    todo.rank = new_rank
                else:
                    todo.rank += delta

            type(self).objects.bulk_update(todos, fields=['rank'])

polls/views.py
from django.shortcuts import render, HttpResponse

def index(request):
    print(request)
    return HttpResponse("Hello, world. You're at the polls app index.")

todo/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Todo


def index(request):
    return render(request, 'todo/index.html', {})


def todo_list_partial(request):
    todos = Todo.objects.all()
    return render(request, 'todo/todo_list_partial.html', {'todos': todos})


def create(request):
    Todo.create(title=request.POST['title'], text=request.POST['text'])
    response = render(request, 'todo/index.html', {})
    response['HX-Redirect'] = request.META['HTTP_HX_CURRENT_URL']
    return response


def todo_details_partial(request, pk):
    todo = get_object_or_404(Todo, pk=pk)

    if request.method == 'GET':
        return render(request, 'todo/todo_details_partial.html', {'todo': todo})
    elif request.method == 'DELETE':
        todo.delete()
    elif request.method == 'PUT':
        todo.title = request.PUT[f'todo_{pk}_title']
        todo.text = request.PUT[f'todo_{pk}_text']
        todo.save()

    todos = Todo.objects.all()
    return render(request, 'todo/todo_list_partial.html', {'todos': todos})


def rerank(request):
    # print(request.POST.getlist('todo_order'))
    reranked = [int(item) for item in request.POST.getlist('todo_order')]
    Todo.rerank_by_list(reranked)
    return HttpResponse(status=204)

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.rawgit.com/kimeiga/bahunya/css/bahunya-0.1.3.css"
    />
    <style type="text/css">
      .col-element {
        width: 50%;
      }
      .left {
        float: left;
      }
      .right {
        float: right;
      }
      .clearfix {
        clear: both;
      }
      .clickable {
        cursor: pointer;
      }
    </style>
    <title>Todo</title>
  </head>
  <body>
    <header>
      <nav>
        <h1><a href="{% url 'todo:index' %}">Todo</a></h1>
        <input type="checkbox" id="menu-toggle" />
        <label for="menu-toggle">&#9776;</label>
        <a href="#">STARTUP</a>
        <a href="#">MINIMAL</a>
        <a href="#">BOLD</a>
      </nav>
      <h1>Todo</h1>
    </header>

    <main>
      <section class="left col-element">
        <h3>Todo List</h3>
        <div
          id="todo_list"
          hx-swap="outerHTML"
          hx-get="{%url 'todo:todo_list_partial' %}"
          hx-trigger="load"
        ></div>
      </section>
      <section class="right col-element">
        <h3>Add Todo</h3>
        <form>
          <fieldset>
            <input type="text" name="title" size="30" placeholder="Title" />
            <textarea
              name="text"
              width="30"
              height="5"
              placeholder="Text"
            ></textarea>
            <button
              hx-post="{% url 'todo:create' %}"
              xh-trigger="click"
              hx-swap="none"
              target="html"
            >
              Submit
            </button>
          </fieldset>
        </form>
      </section>
      <div class="clearfix"></div>
    </main>

    <footer>That's all, folks!</footer>

    <script
      src="https://unpkg.com/htmx.org@1.5.0"
      integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
    <script>
      document.body.addEventListener("htmx:configRequest", (event) => {
        event.detail.headers["X-CSRFToken"] = "{{ csrf_token }}";
      });
      htmx.onLoad(function (content) {
        var sortables = content.querySelectorAll(".sortable");
        for (var i = 0; i < sortables.length; i++) {
          var sortable = sortables[i];
          new Sortable(sortable, {
            animation: 150,
            ghostClass: "blue-background-class",
          });
        }
      });
    </script>
  </body>
</html>

todo/templates/todo/todo_details_partial.html
<div id="todo_{{todo.pk}}">
  <form>
    <fieldset>
      <div>
        <input
          type="text"
          name="todo_{{todo.pk}}_title"
          value="{{todo.title}}"
        />
      </div>
      <div>
        <textarea name="todo_{{todo.pk}}_text" rows="5" cols="20">
{{todo.text}}</textarea
        >
      </div>
      <button
        hx-put="{% url 'todo:todo_details_partial' todo.pk %}"
        hx-target="#todo_list"
        hx-swap="outerHTML"
      >
        Update
      </button>
      <button
        hx-delete="{% url 'todo:todo_details_partial' todo.pk %}"
        hx-target="#todo_list"
        hx-swap="outerHTML"
      >
        Delete
      </button>
    </fieldset>
  </form>
</div>

todo/templates/todo/todo_list_partial.html
<div id="todo_list">
  <ol
    class="sortable"
    hx-post="{% url 'todo:rerank' %}"
    hx-include="[name='todo_order']"
    hx-trigger="end"
  >
    {% for todo in todos %}
    <li>
      <div
        id="todo_{{todo.pk}}"
        class="clickable"
        hx-get="{% url 'todo:todo_details_partial' todo.pk %}"
        hx-trigger="click"
        hx-target="this"
        hx-swap="outerHTML"
      >
        <div>{{todo.title}}</div>
        <input type="hidden" name="todo_order" value="{{todo.pk}}" />
      </div>
    </li>
    {% endfor %}
  </ol>
</div>